=== icerahi1/web_service_assignment1/src/resources/student.dtd
<!ELEMENT student (id, name, age, gpa, isInternational, gradeLevel, subjects)>
        <!ELEMENT id (#PCDATA)>
        <!ELEMENT name (#PCDATA)>
        <!ELEMENT age (#PCDATA)>
        <!ELEMENT gpa (#PCDATA)>
        <!ELEMENT isInternational (#PCDATA)>
        <!ELEMENT gradeLevel (#PCDATA)>
        <!ELEMENT subjects (subject+)>
        <!ELEMENT subject (#PCDATA)>

=== icerahi1/web_service_assignment1/received_student.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE student SYSTEM "src/resources/student.dtd">
<student>
    <id>101</id>
    <name>John Doe</name>
    <age>22</age>
    <gpa>3.8</gpa>
    <isInternational>true</isInternational>
    <gradeLevel>A</gradeLevel>
    <subjects>
        <subject>Mathematics</subject>
        <subject>Physics</subject>
        <subject>Chemistry</subject>
        <subject>Biology</subject>
        <subject>History</subject>
        <subject>Geography</subject>
        <subject>Literature</subject>
        <subject>Computer Science</subject>
        <subject>Art</subject>
        <subject>Physical Education</subject>
    </subjects>
</student>
